apiVersion: v1
kind: Service
metadata:
  name: k8s-bootcamp-svc
  labels:
    app: k8s-bootcamp-app
spec:
  type: NodePort # Default is ClusterIP if not specified
  selector:
    app: k8s-bootcamp # match the Pod labelllll
  ports:
  - port: 8888 
    targetPort: 8080 # targetPort is optional if same as port number
    protocol: TCP
