apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: development # specify the namespace here
  labels:
    app: webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80 #port
      protocol: TCP
